### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by lpinca**
This adds a proper `LICENSE` file that will be included in the npm package.

### CODE REVIEW

**Comment by alexandresaiz** [comment]
@lpinca not a big deal, but we normally want to have ANY microapps url tagged. When viewing this readme file from a browser within GH it's indeed clickable. Anyway, Analytics does track the referer too. It's just a matter of following the same concept always.

**Comment by lpinca** [comment]
@alexandresaiz This is how you'll see it on GitHub https://github.com/lpinca/Nodify/blob/ce413f15cdabfd4c749aa64a2ab80d131ecc3191/LICENSE

**Comment by lpinca** [comment]
Anyway no problem, I will add the query string back.

**Comment by lpinca** [comment]
Done.

**Comment by alexandresaiz** [comment]
@lpinca I was confused between the readme and the license file. Sorry.

**Pull request merged**
